# Файл docker-compose.yml

# Версия docker-compose
version: '3'

# Перечень volume
volumes:
  pg_data:

# Перечень контейнеров
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
  frontend:
    env_file: .env
    build: ./frontend/
  gateway:
    build: ./gateway/
    ports:
      - 8000:80